{{- if .Values.brain.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-brain-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.brain.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.brain.persistence.size }}
  {{- if .Values.brain.persistence.storageClass }}
  storageClassName: {{ .Values.brain.persistence.storageClass }}
  {{- end }}
{{- end -}}
