{{- if .Values.agent.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-agent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Release.Name }}-agent
  minReplicas: {{ .Values.agent.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.agent.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.agent.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.agent.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.agent.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.agent.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if .Values.agent.autoscaling.customMetrics }}
{{ toYaml .Values.agent.autoscaling.customMetrics | indent 4 }}
  {{- end }}
{{- end }}
