theme: jekyll-theme-minimal
title: Simple CLI
description: Advanced Autonomous Agent Workforce
header_pages:
  - index.md
  - demos/oil_gas.md
  - demos/developer.md
  - benchmarks/dashboard/index.html
